* idea plugin: maintenance, migration to platform plugin v2, fixes for crashes/failures due SDK missing (#849)
* * idea plugin: 2025.2 was crashing due kotlin incompatibility, failure due SDK missing

1. 2025.2 ships with kotline 2.1
```
Exception in thread "ApplicationImpl pooled thread 4" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[BlockingEventLoop@38722215, org.robovm.idea.sdk.RoboVmSdkUnpackService$extractSdkIfNeeded$3$2@2f934f6b]){Completed}@15d7991d. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:130)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
```

2. if SDK was deleted from disk, it wasn't re-installed. That caused exception:
```
java.lang.RuntimeException: java.io.IOException: listFiles failed on /Users/niagara/.robovm-sdks/robovm-2.3.25/lib
	at org.robovm.idea.RoboVmPlugin.getSdkLibraries(RoboVmPlugin.java:257)
	at org.robovm.idea.RoboVmPlugin.getSdkLibrariesWithoutSources(RoboVmPlugin.java:267)
	at org.robovm.idea.compilation.RoboVmCompileTask.configureClassAndSourcepaths(RoboVmCompileTask.java:360)
```

* * idea plugin: maintenance -- migrated to platform plugin, gradle 9.5

changes are required as old gradle plugin messed between K1/K2 compilers with error:
> error: Invalid plugin descriptor 'plugin.xml': failed to resolve <xi:include>. Not found document 'kotlin.plugin.k1.xml' referenced in <xi:include href="kotlin.plugin.k1.xml", includeUnless="idea.kotlin.plugin.use.k2"/>. <xi:fallback> element is not provided. (at plugin.xml)