* fixed: de-sugared ByteBuffer (java9) calls are not visible at second compilation session Root Case: these methods are added when ByteBuffer is compiled. At next session ByteBuffer class is considered compiled and its structure only parsed (and not desugared) as result de-sugared methods are not present in SootClass as result this produces `java.lang.NoSuchMethodError` compilation time.
Fix: in trampoline allow compiler plugin to resolve missing methods. ByteBuffer de-sugaring plugin in this case returns references to target methods.