* desugar: added compiler plugin that extends ByteBuffer with Java9 API ## Overview Java9 adds overridden methods with covariant return types in ByteBuffer: - flip - clear - mark - reset - rewind - position - limit It becomes problem when using external dependency that was compiled as `-release 9` and caused exceptions: > java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer The only options is to re-compile the dependency. But it is not always possible.
## Discussion
This might be achieved by just adapting runtime classes but having it as Plugin allows to enable or disable the behaviour.

## Other changes
Desugar plugins were extended with option to disable using plugin arguments:
```
<pluginArguments>
    <argument>desugar:enableJdk9ByteBufferApi=false</argument>
    <argument>desugar:enableJava9StringConcat=false</argument>
</pluginArguments>
```