jdk12 into master (preparation) (#470)
* * simlauncher stopped working with ios13. switching to apple's simctl instead. (#402)

* * xcode11 fix. swift libraries not in /swift/ directory anymore but in swift-5.0. it is not a perfect fix but dirty workaround but it allows to use swift based frameworks with xcode11 (#405)

* Ios13 switch to simctl -- starting simulator (#410)

* * simlauncher stopped working with ios13. switching to apple's simctl instead.

* * added 'open Simulator' as simctl boot doesn't show the simulator and it has to be opened either using spotlight or open cmd

* #414 fix (libimobiledevice affected) (#416)

* updated to recent master of libimobiledevice which should fix the issue:
- removed libxml as it not required anymore by libplist v2.0.0
- libusbmuxd is picked from master, as version 1.1.0 is not available in releases
- added openssl as dependency as it is not part of MacOSX anymore (probably LibreSSL might be used)

* * fixed libmobiledevice to allow bypass ssl termination when required

* * libimobiledevice: bindings re-generated to recent version with ssl  passthrough and debug server

* * libimobiledevice: added handling of introduced time-out

* * libimobiledevice: added patch to provide timeout error through debugserver client

* * libimobiledevice: added patch to provide timeout error through debugserver client

* * libimobiledevice: removed unused debugserver api, fixed unix permissions for all other files

* * libimobiledevice: switched to use DebugServerClient to interact with GDB server, cleaned up some if lint warnings in AppLauncher and fixed to dev image lookup to allow using older one available (for example to use 13.0 with 13.1 device)

* * libimobiledevice: reverted back companion to byte[] parameter `count` argument. As usually byte array buffer contains less useful bytes than its length (this broke upload of app)

* update libimobiledevice lib

* * fixed broken reg-exp for version matching (development image lookup), added testcases for new code (#427)

* * fixed #408 by adding @MarshalsValue to toNative methods. Otherwise compiler was not able to resolve to native marshaller for enum and went to parent class where it picked up default marshaller from ValuedEnum. This results in type difference in case type of enum data is not int and caused following exception: (#409)

> java.lang.IllegalArgumentException: Duplicate @StructMember(1) in @Packed structs (union in packed structs is not supported

* Add bool declarations for non Darwin systems (#425)

* [maven-release-plugin] prepare release robovm-2.3.8

* [maven-release-plugin] prepare for next development iteration

* Set release version of Eclipse plugin, 2.3.8

* Set next development version of Eclipse plugin, 2.3.9

* Set release version of IDEA plugin, 2.3.8

* Set next development version of IDEA plugin, 2.3.9

* Set release version of Gradle plugin, 2.3.8

* Set next development version of Gradle plugin, 2.3.9-SNAPSHOT

* Update commons-compress due to security vulnerability

* * reworked simulator device types. doesn't depend on SDK versions available (#436)

* Switch use of maven http to https since http is no longer supported. (#452)

* Fixes min OS version checks and removes hardcoded values (#463)

* Fixes min OS version checks and removes hardcoded values

* Use getInfoPlist(9 on FrameworkTarget

* Use getMinimumIosVersion()

* [maven-release-plugin] prepare release robovm-2.3.9

* [maven-release-plugin] prepare for next development iteration

* Set release version of Eclipse plugin, 2.3.9

* Set next development version of Eclipse plugin, 2.3.10

* Set release version of IDEA plugin, 2.3.9

* Set next development version of IDEA plugin, 2.3.10

* Set release version of Gradle plugin, 2.3.9

* Set next development version of Gradle plugin, 2.3.10-SNAPSHOT

Co-authored-by: Tom-Ski <tomwojciechowski@asidik.com>
Co-authored-by: legion151 <42674335+legion151@users.noreply.github.com>
Co-authored-by: Justin Shapcott <justin@mobidevelop.com>
Co-authored-by: Eric Nondahl <ericnondahl@users.noreply.github.com>