* fixed #408 by adding @MarshalsValue to toNative methods. Otherwise compiler was not able to resolve to native marshaller for enum and went to parent class where it picked up default marshaller from ValuedEnum. This results in type difference in case type of enum data is not int and caused following exception: (#409)
> java.lang.IllegalArgumentException: Duplicate @StructMember(1) in @Packed structs (union in packed structs is not supported