* fixed: debugger crash Cannot read the array length because "interfaces" is null (#816)
```
 java.lang.NullPointerException: Cannot read the array length because "interfaces" is null
	at org.robovm.debugger.jdwp.handlers.referencetype.JdwpRefTypeInterfacesHandler.handle(JdwpRefTypeInterfacesHandler.java:49)
	at org.robovm.debugger.jdwp.JdwpDebugServer.doSocketWork(JdwpDebugServer.java:200)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.robovm.debugger.utils.DebuggerThread.run(DebuggerThread.java:42)
```

## Root case:
debugger queries interface information for classes that are marked as `ClassStatus.ERROR`.
> java8/util/DelegatingSpliterator$ConsumerDelegate has error 1 due java.util.function.Consumer
and
> Class was Warning: java.util.function.Consumer is a phantom class!

## the fix: initialize fields with empty arrays.

## other changes:
- using 10 threads for maven builds
- printing line numbers in stacktraces in debug output

Co-authored-by: Tomski <tomwojciechowski@asidik.com>