* fixed: failed to parse DeviceCtl response on Xcode27 Beta (#860)
> java.lang.NumberFormatException: For input string: "18446744071562067970"

root case: `com.googlecode.json-simple:1.1.1` supports biggest number that fit into Long only and will fail on any bigger.
as a quick fix will switch to last known and maintained fork `com.github.cliftonlabs:4.0.1`

```
"hardware" : {
            "cpuType" : {
              "subtype" : 18446744071562067970,
              "type" : 16777228
            },
            "ecid" : 3502134164946974,
            "productType" : "iPhone14,6",
            "udid" : "00008110-000C712C26DB801E"
          },
```