BCLE library was not packed into release plugin jar which caused java.lang.NoClassDefFoundError: org/apache/bcel/classfile/ClassParser exception (#225)